name: ShadowAntiCheat
main: DarkWav\SAC\Main
version: 4.0.17
authors: ["DarkWav", "radondev"]
api: [3.0.0]
commands:
  shadowanticheat:
    description: Shows ShadowAntiCheat version.
    aliases: ["ShadowAntiCheat","sac","SAC","anticheat","AntiCheat"]
