name: ShadowAntiCheat
main: DarkWav\SAC\Main
version: 4.0.12
author: DarkWav
api: [3.0.0]
commands:
  sac:
    description: Shows ShadowAntiCheat version.
    aliases: ["ShadowAntiCheat","AntiCheat","SAC"]
  shadowanticheat:
    description: Shows ShadowAntiCheat version.
    aliases: ["ShadowAntiCheat","AntiCheat","SAC"]
